### ISSUE TITLE
Cannot generate html pages on production mode

### ISSUE THREAD

**Issue by daneget** [researchgate/path-chunk-webpack-plugin#1]
I'm preparing to develop an application and with others plugins I included this and the HtmlWebpackPlugin. I use PathChunkPlugin to generate a vendor chunk with node modules and the HtmlWebpackPlugin for generate the pages for each entry.

The problem is than when I try to run webpack in production mode, the page generation is throwing an error that it seem to be related with webpack's OccurrenceOrderPlugin, because if I disable it, the generation is ok.

After that and because I haven't this problem with CommonsChunkPlugin, I compare this plugin source code with CommonsChunkPlugin and I have found that compiler and compilation configuration is different.

[CommonsChunkPlugin](https://github.com/webpack/webpack/blob/master/lib/optimize/CommonsChunkPlugin.js#L47-L48)

```
compiler.plugin("this-compilation", function(compilation) {
  compilation.plugin(["optimize-chunks", "optimize-extracted-chunks"], function(chunks) {
```

[PathChunkPlugin](https://github.com/researchgate/path-chunk-webpack-plugin/blob/master/index.js#L42-L43)

```
compiler.plugin('compilation', function (compilation) {
  compilation.plugin('optimize-chunks', function (chunks) {
```

I've test to change this two lines on PathChunkPlugin and It seems to works well.

Can you test it? and update plugins source code?

Thanks

**Comment by danez** [comment]
This plugin is deprecated. You should use CommonsChunkPlugin with minChunks set to a callback. 
https://webpack.js.org/plugins/commons-chunk-plugin/#passing-the-minchunks-property-a-function
