### ISSUE TITLE
Doesn't work with webpack 2

### ISSUE THREAD

**Issue by tomasAlabes** [researchgate/path-chunk-webpack-plugin#2]
Tried to use it with webpack 2 and I had this error:

```
basic chunk optimization>> Error: Chunk.entry was removed. Use hasRuntime()
>>   at Chunk.Object.defineProperty.set (node_modules/webpack/lib/Chunk.js:37:9)
>>   at Compilation.<anonymous> (node_modules/path-chunk-webpack-plugin/index.js:54:45)
```

Time to have a different release for webpack 2?

**Comment by danez** [comment]
We are currently not using this plugin and therefore haven't tested it with webpack 2.
Would you like to supply a PR maybe? I could also add someone to the repo, who is actively using this plugin.

**Comment by tomasAlabes** [comment]
Hi @danez, thanks for the quick reply. I ended up forking another plugin and adapting it to webpack 2 ([plugin](https://github.com/tomasAlabes/webpack2-externals-plugin)). But if I have time I will take a look at this, it should be easy to adapt.

**Comment by danez** [comment]
You can use CommonsChunkPlugin with minChunks set to a callback. That's why I deprecated the plugin now.
https://webpack.js.org/plugins/commons-chunk-plugin/#passing-the-minchunks-property-a-function
